# Generated by Django 4.1.4 on 2022-12-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Delhi', 'Delhi'), ('Noida', 'Noida'), ('Bangalore', 'Bangalore')], max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('pimage', models.ImageField(blank=True, upload_to='pimages')),
                ('rdoc', models.FileField(blank=True, upload_to='rdoc')),
            ],
        ),
    ]
